name: Keep Repo Active

on:
  schedule:
    # Run once a week at midnight UTC on Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep repo active
        run: echo "Keeping the repository active so scheduled workflows don't pause"
