name: Wake Streamlit App

on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:         # allow manual trigger

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script
        run: python wake_up_streamlit.py

      - name: Upload log file as artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: wakeup-log 
          path: wakeup_log.txt
